import os
import sys
from src.generation import generate_pdf

# Intentional malformed Markdown (no newline before header)
MALFORMED_MARKDOWN = """
# Inspection Report: Formatting Fix Test
This is a paragraph that ends without a newline## 2. AREA-WISE OBSERVATIONS
- **Bold Test**: This should definitely be bold **now**.
- **Header Merget Test**: The header above '2. AREA-WISE OBSERVATIONS' was merged in the source but should be fixed.

---
**Generated by AI DDR System**
*Note: verify all structural recommendations with a licensed professional.*
"""

def test_pdf():
    print("Generating test PDF with malformed headers...")
    pdf_bytes = generate_pdf(MALFORMED_MARKDOWN)
    
    if pdf_bytes:
        with open("test_formatting_fix.pdf", "wb") as f:
            f.write(pdf_bytes)
        print(f"Success! Test PDF generated: {os.path.abspath('test_formatting_fix.pdf')}")
        print(f"Size: {len(pdf_bytes)} bytes")
    else:
        print("Failure: PDF generation returned empty bytes.")

if __name__ == "__main__":
    test_pdf()
